from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import TYPE_CHECKING
import json
import os

from .models import FirmwareContext, RagHit, SCHEMA_VERSION

if TYPE_CHECKING:  # pragma: no cover - import cycle guard for type checkers only
    from .inference import InferenceOptions
    from .reference_db import PeripheralRange


class ProviderError(RuntimeError):
    """Raised when an inference provider cannot return a raw response."""


@dataclass(frozen=True)
class ProviderResponse:
    raw_text: str
    provider_used: str
    network_performed: bool = False


def call_provider(
    options: InferenceOptions,
    prompt: str,
    context: FirmwareContext,
    device: str,
    rag_hits: list[RagHit],
    memory_ranges: list[PeripheralRange],
) -> ProviderResponse:
    if options.provider == "mock":
        return ProviderResponse(
            raw_text=_mock_response(options, context, device, rag_hits),
            provider_used="mock",
            network_performed=False,
        )
    if options.provider == "openai":
        return _openai_response(options, prompt)
    if options.provider == "local":
        raise ProviderError(
            "local LLM provider is reserved but not configured; use deterministic, mock, or openai"
        )
    raise ProviderError(f"unsupported LLM provider: {options.provider}")


def _mock_response(
    options: InferenceOptions,
    context: FirmwareContext,
    device: str,
    rag_hits: list[RagHit],
) -> str:
    if options.mock_response_path:
        return Path(options.mock_response_path).read_text(encoding="utf-8")

    case = options.mock_response
    if case == "invalid-json":
        return "{not valid json"
    if case == "provider-error":
        raise ProviderError("mock provider-error case requested")

    payload = _valid_mock_payload(context, device, rag_hits)
    if case == "missing-field" and payload["findings"]:
        payload["findings"][0].pop("confidence", None)
    elif case == "low-confidence" and payload["findings"]:
        payload["findings"][0]["confidence"] = -0.1
    elif case != "valid":
        raise ProviderError(f"unknown mock response case: {case}")
    return json.dumps(payload, ensure_ascii=False)


def _valid_mock_payload(
    context: FirmwareContext,
    device: str,
    rag_hits: list[RagHit],
) -> dict[str, object]:
    address = context.mmio_addresses[0] if context.mmio_addresses else "0x40000000"
    return {
        "schema_version": SCHEMA_VERSION,
        "device": device,
        "findings": [
            {
                "mmio_address": address,
                "type": "MMIO",
                "action": "map_dummy_mmio",
                "value": "0x00000000",
                "confidence": 0.7,
                "evidence": [
                    "mock provider fixture",
                    f"architecture_hint={context.architecture_hint}",
                ],
                "peripheral_name": None,
                "reference_range": None,
                "reference_source": rag_hits[0].source if rag_hits else None,
            }
        ],
        "rag_hits": [asdict(hit) for hit in rag_hits],
        "assumptions": ["Generated by offline mock provider fixture."],
    }


def _openai_response(options: InferenceOptions, prompt: str) -> ProviderResponse:
    if not os.environ.get("OPENAI_API_KEY"):
        raise ProviderError("OPENAI_API_KEY is not set; openai provider is opt-in and requires credentials")
    try:
        from openai import OpenAI  # type: ignore[import-not-found]
    except ImportError as exc:  # pragma: no cover - depends on optional extra
        raise ProviderError("openai package is not installed; install with pip install -e '.[llm]'") from exc

    schema = {
        "type": "object",
        "required": ["schema_version", "device", "findings", "rag_hits", "assumptions"],
        "additionalProperties": True,
        "properties": {
            "schema_version": {"type": "string"},
            "device": {"type": "string"},
            "findings": {"type": "array"},
            "rag_hits": {"type": "array"},
            "assumptions": {"type": "array", "items": {"type": "string"}},
        },
    }
    client = OpenAI(timeout=options.timeout_seconds)
    response = client.responses.create(
        model=os.environ.get("OPENAI_MODEL", "gpt-5"),
        input=prompt,
        text={
            "format": {
                "type": "json_schema",
                "name": "firmware_inference_result",
                "schema": schema,
                "strict": False,
            }
        },
    )
    raw_text = getattr(response, "output_text", None)
    if not isinstance(raw_text, str) or not raw_text.strip():
        raise ProviderError("OpenAI response did not contain output_text")
    return ProviderResponse(
        raw_text=raw_text[: options.max_raw_response_chars],
        provider_used="openai",
        network_performed=True,
    )
